export const SHOW_USERS_LOADER = 'SHOW_USERS_LOADER';
export const HIDE_USERS_LOADER = 'HIDE_USERS_LOADER';
export const SET_USERS_LIST = 'SET_USERS_LIST';

export const SHOW_POSTS_LOADER = 'SHOW_POSTS_LOADER';
export const HIDE_POSTS_LOADER = 'HIDE_POSTS_LOADER';
export const SET_POSTS_LIST = 'SET_POSTS_LIST';
